//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllSalesMainCustomer
    {
        public int Id { get; set; }
        public string IdSale { get; set; }
        public string CustomerId { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public Nullable<System.DateTime> CustomerBirthday { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerCellphone { get; set; }
        public string CustomerGender { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string StatesId { get; set; }
        public string CityId { get; set; }
        public string CustomerZipCode { get; set; }
        public string CustomerStreet { get; set; }
        public string CustomerPlateNumber { get; set; }
        public string CustomerComplement { get; set; }
        public string CustomerNameMother { get; set; }
        public Nullable<int> PlanId { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public string SellerCode { get; set; }
        public string BuyerName { get; set; }
        public string BuyerCellPhone { get; set; }
        public string BuyerEmail { get; set; }
        public string CompanySaleId { get; set; }
        public Nullable<int> Mainly { get; set; }
        public string MainlyId { get; set; }
        public string url { get; set; }
        public Nullable<int> Bus { get; set; }
        public string IdSaleMainly { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<System.DateTime> SaleDate2 { get; set; }
        public Nullable<System.DateTime> BeginingDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
