//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppXUser
    {
        public int Id { get; set; }
        public Nullable<int> IdAppContract { get; set; }
        public string IdUser { get; set; }
        public Nullable<int> idProd { get; set; }
    
        public virtual AppContract AppContract { get; set; }
        public virtual users users { get; set; }
    }
}
