//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BopDb : DbContext
    {
        public BopDb()
            : base("name=BopDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AddressXUser> AddressXUser { get; set; }
        public DbSet<AllSalesMainCustomer> AllSalesMainCustomer { get; set; }
        public DbSet<AppContract> AppContract { get; set; }
        public DbSet<application_area> application_area { get; set; }
        public DbSet<appoiment> appoiment { get; set; }
        public DbSet<apps> apps { get; set; }
        public DbSet<AppXUser> AppXUser { get; set; }
        public DbSet<ar> ar { get; set; }
        public DbSet<cards> cards { get; set; }
        public DbSet<characteristic_treatment> characteristic_treatment { get; set; }
        public DbSet<city> city { get; set; }
        public DbSet<claims> claims { get; set; }
        public DbSet<collections> collections { get; set; }
        public DbSet<commission> commission { get; set; }
        public DbSet<CommissionForSale> CommissionForSale { get; set; }
        public DbSet<configurationXcontractXproducts> configurationXcontractXproducts { get; set; }
        public DbSet<contract> contract { get; set; }
        public DbSet<contractXproducts> contractXproducts { get; set; }
        public DbSet<country> country { get; set; }
        public DbSet<currency> currency { get; set; }
        public DbSet<de> de { get; set; }
        public DbSet<en> en { get; set; }
        public DbSet<entity> entity { get; set; }
        public DbSet<entitycontract> entitycontract { get; set; }
        public DbSet<entitytype> entitytype { get; set; }
        public DbSet<es> es { get; set; }
        public DbSet<Excepciones> Excepciones { get; set; }
        public DbSet<externalUserId> externalUserId { get; set; }
        public DbSet<fa> fa { get; set; }
        public DbSet<glosas> glosas { get; set; }
        public DbSet<glosastatusclaims> glosastatusclaims { get; set; }
        public DbSet<glosaXtreatments> glosaXtreatments { get; set; }
        public DbSet<groupXentity> groupXentity { get; set; }
        public DbSet<gto> gto { get; set; }
        public DbSet<gtoclaims> gtoclaims { get; set; }
        public DbSet<homologacion> homologacion { get; set; }
        public DbSet<homologationUpstream> homologationUpstream { get; set; }
        public DbSet<impuesto> impuesto { get; set; }
        public DbSet<impuestoXcountry> impuestoXcountry { get; set; }
        public DbSet<InformationAditionalXApp> InformationAditionalXApp { get; set; }
        public DbSet<infoXcontractXprod> infoXcontractXprod { get; set; }
        public DbSet<invoices> invoices { get; set; }
        public DbSet<languages> languages { get; set; }
        public DbSet<LogWs> LogWs { get; set; }
        public DbSet<menus> menus { get; set; }
        public DbSet<neighborhood> neighborhood { get; set; }
        public DbSet<network> network { get; set; }
        public DbSet<otherproducts> otherproducts { get; set; }
        public DbSet<paymentgatewayXentity> paymentgatewayXentity { get; set; }
        public DbSet<paymenttype> paymenttype { get; set; }
        public DbSet<periodinactivation> periodinactivation { get; set; }
        public DbSet<periodpayment> periodpayment { get; set; }
        public DbSet<permissionsXmenu> permissionsXmenu { get; set; }
        public DbSet<products> products { get; set; }
        public DbSet<productsXcountry> productsXcountry { get; set; }
        public DbSet<productsXotherproducts> productsXotherproducts { get; set; }
        public DbSet<productsXtreatments> productsXtreatments { get; set; }
        public DbSet<productXapp> productXapp { get; set; }
        public DbSet<providers> providers { get; set; }
        public DbSet<providerXcontract> providerXcontract { get; set; }
        public DbSet<pt> pt { get; set; }
        public DbSet<RandomSaleId> RandomSaleId { get; set; }
        public DbSet<roles> roles { get; set; }
        public DbSet<sales> sales { get; set; }
        public DbSet<services> services { get; set; }
        public DbSet<servicesXapp> servicesXapp { get; set; }
        public DbSet<servicesXnetwork> servicesXnetwork { get; set; }
        public DbSet<servicesXproduct> servicesXproduct { get; set; }
        public DbSet<specialty> specialty { get; set; }
        public DbSet<states> states { get; set; }
        public DbSet<status> status { get; set; }
        public DbSet<statusclaims> statusclaims { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<token> token { get; set; }
        public DbSet<tooth> tooth { get; set; }
        public DbSet<treatments> treatments { get; set; }
        public DbSet<treatmentsXcountry> treatmentsXcountry { get; set; }
        public DbSet<typeparticipation> typeparticipation { get; set; }
        public DbSet<typeprovider> typeprovider { get; set; }
        public DbSet<typeXviews> typeXviews { get; set; }
        public DbSet<uctreatconuntry> uctreatconuntry { get; set; }
        public DbSet<useraudituc> useraudituc { get; set; }
        public DbSet<users> users { get; set; }
        public DbSet<usersXentity> usersXentity { get; set; }
        public DbSet<usersXgroup> usersXgroup { get; set; }
        public DbSet<usersXprovider> usersXprovider { get; set; }
        public DbSet<usertypeXapp> usertypeXapp { get; set; }
        public DbSet<validitytime> validitytime { get; set; }
        public DbSet<channels> channels { get; set; }
        public DbSet<commentaryXticket> commentaryXticket { get; set; }
        public DbSet<priorityXticket> priorityXticket { get; set; }
        public DbSet<statusXticket> statusXticket { get; set; }
        public DbSet<subjectXticket> subjectXticket { get; set; }
        public DbSet<ticket> ticket { get; set; }
        public DbSet<typeXticket> typeXticket { get; set; }
        public DbSet<visibilityXcommentary> visibilityXcommentary { get; set; }
        public DbSet<borrar_users> borrar_users { get; set; }
        public DbSet<rolesXuser> rolesXuser { get; set; }
    }
}
