//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class characteristic_treatment
    {
        public int chatreat_id { get; set; }
        public string chatreat_description { get; set; }
        public int apparea_id { get; set; }
        public int speci_id { get; set; }
        public int tooth_id { get; set; }
        public int treat_id { get; set; }
    
        public virtual application_area application_area { get; set; }
        public virtual specialty specialty { get; set; }
        public virtual tooth tooth { get; set; }
        public virtual treatments treatments { get; set; }
    }
}
