//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class claims
    {
        public claims()
        {
            this.gtoclaims = new HashSet<gtoclaims>();
            this.statusclaims = new HashSet<statusclaims>();
        }
    
        public int claim_id { get; set; }
        public double claim_treatcomplex { get; set; }
        public double claim_provucfactor { get; set; }
        public double claim_utreatcovalue { get; set; }
        public int claim_portrecoverage { get; set; }
        public System.DateTime claim_creationdate { get; set; }
        public double claim_basevalue { get; set; }
        public double claim_uservalue { get; set; }
        public double claim_tpavalue { get; set; }
        public int treat_id { get; set; }
    
        public virtual treatments treatments { get; set; }
        public virtual ICollection<gtoclaims> gtoclaims { get; set; }
        public virtual ICollection<statusclaims> statusclaims { get; set; }
    }
}
