//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class collections
    {
        public int colle_id { get; set; }
        public int colle_periodpayment { get; set; }
        public double calle_value { get; set; }
        public int invo_id { get; set; }
    
        public virtual invoices invoices { get; set; }
    }
}
