//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class commission
    {
        public int comi_id { get; set; }
        public double comi_participation { get; set; }
        public int typepartici_id { get; set; }
        public int contractprod_id { get; set; }
        public int groupenti_id { get; set; }
        public int role_id { get; set; }
    
        public virtual contractXproducts contractXproducts { get; set; }
        public virtual groupXentity groupXentity { get; set; }
        public virtual typeparticipation typeparticipation { get; set; }
        public virtual roles roles { get; set; }
    }
}
