//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class configurationXcontractXproducts
    {
        public configurationXcontractXproducts()
        {
            this.sales = new HashSet<sales>();
        }
    
        public int confcontractprod_id { get; set; }
        public int contractprod_id { get; set; }
        public double confcontractprod_value { get; set; }
        public int curren_id { get; set; }
        public int info_id { get; set; }
        public int vtime_id { get; set; }
        public int ppay_id { get; set; }
    
        public virtual contractXproducts contractXproducts { get; set; }
        public virtual currency currency { get; set; }
        public virtual infoXcontractXprod infoXcontractXprod { get; set; }
        public virtual periodpayment periodpayment { get; set; }
        public virtual validitytime validitytime { get; set; }
        public virtual ICollection<sales> sales { get; set; }
    }
}
