//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class contractXproducts
    {
        public contractXproducts()
        {
            this.commission = new HashSet<commission>();
            this.configurationXcontractXproducts = new HashSet<configurationXcontractXproducts>();
            this.gto = new HashSet<gto>();
        }
    
        public int contractprod_id { get; set; }
        public int contractprod_wp { get; set; }
        public int contractprod_recurrent { get; set; }
        public int product_id { get; set; }
        public int contract_id { get; set; }
        public Nullable<double> contractprod_participation { get; set; }
        public Nullable<int> contractprod_idfather { get; set; }
        public Nullable<int> typepartici_id { get; set; }
    
        public virtual ICollection<commission> commission { get; set; }
        public virtual ICollection<configurationXcontractXproducts> configurationXcontractXproducts { get; set; }
        public virtual contract contract { get; set; }
        public virtual contract contract1 { get; set; }
        public virtual products products { get; set; }
        public virtual typeparticipation typeparticipation { get; set; }
        public virtual ICollection<gto> gto { get; set; }
    }
}
