//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public country()
        {
            this.entity = new HashSet<entity>();
            this.impuestoXcountry = new HashSet<impuestoXcountry>();
            this.periodinactivation = new HashSet<periodinactivation>();
            this.productsXcountry = new HashSet<productsXcountry>();
            this.states = new HashSet<states>();
            this.treatmentsXcountry = new HashSet<treatmentsXcountry>();
            this.uctreatconuntry = new HashSet<uctreatconuntry>();
            this.users = new HashSet<users>();
        }
    
        public int country_id { get; set; }
        public string country_name { get; set; }
        public string country_continent { get; set; }
        public string country_nameNative { get; set; }
    
        public virtual ICollection<entity> entity { get; set; }
        public virtual ICollection<impuestoXcountry> impuestoXcountry { get; set; }
        public virtual ICollection<periodinactivation> periodinactivation { get; set; }
        public virtual ICollection<productsXcountry> productsXcountry { get; set; }
        public virtual ICollection<states> states { get; set; }
        public virtual ICollection<treatmentsXcountry> treatmentsXcountry { get; set; }
        public virtual ICollection<uctreatconuntry> uctreatconuntry { get; set; }
        public virtual ICollection<users> users { get; set; }
    }
}
