//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class currency
    {
        public currency()
        {
            this.configurationXcontractXproducts = new HashSet<configurationXcontractXproducts>();
            this.paymentgatewayXentity = new HashSet<paymentgatewayXentity>();
            this.uctreatconuntry = new HashSet<uctreatconuntry>();
        }
    
        public int curren_id { get; set; }
        public string curren_description { get; set; }
    
        public virtual ICollection<configurationXcontractXproducts> configurationXcontractXproducts { get; set; }
        public virtual ICollection<paymentgatewayXentity> paymentgatewayXentity { get; set; }
        public virtual ICollection<uctreatconuntry> uctreatconuntry { get; set; }
    }
}
