//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class entitytype
    {
        public entitytype()
        {
            this.entity = new HashSet<entity>();
        }
    
        public int entype_id { get; set; }
        public string entype_description { get; set; }
    
        public virtual ICollection<entity> entity { get; set; }
    }
}
