//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class entity
    {
        public entity()
        {
            this.entitycontract = new HashSet<entitycontract>();
            this.paymentgatewayXentity = new HashSet<paymentgatewayXentity>();
            this.usersXentity = new HashSet<usersXentity>();
        }
    
        public int enti_id { get; set; }
        public string enti_name { get; set; }
        public string enti_nit { get; set; }
        public double enti_latitud { get; set; }
        public double enti_longitud { get; set; }
        public int entype_id { get; set; }
        public int neig_id { get; set; }
        public int country_id { get; set; }
        public int status_id { get; set; }
        public Nullable<int> enti_entifather { get; set; }
        public string enti_description { get; set; }
        public string enti_logo { get; set; }
        public string enti_background { get; set; }
        public string enti_maincolor { get; set; }
        public string enti_seccolor { get; set; }
        public string enti_url { get; set; }
        public string enti_favicon { get; set; }
        public string enti_EmailHolder { get; set; }
        public string enti_EmailCopies { get; set; }
        public string enti_SalesEmail { get; set; }
        public string enti_User { get; set; }
        public string enti_Password { get; set; }
        public string enti_PublicKey { get; set; }
        public string enti_PrivateKey { get; set; }
    
        public virtual country country { get; set; }
        public virtual entitytype entitytype { get; set; }
        public virtual neighborhood neighborhood { get; set; }
        public virtual status status { get; set; }
        public virtual ICollection<entitycontract> entitycontract { get; set; }
        public virtual ICollection<paymentgatewayXentity> paymentgatewayXentity { get; set; }
        public virtual ICollection<usersXentity> usersXentity { get; set; }
    }
}
