//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class glosastatusclaims
    {
        public int glostacla_id { get; set; }
        public int stacla_id { get; set; }
        public int glosa_id { get; set; }
    
        public virtual glosas glosas { get; set; }
        public virtual statusclaims statusclaims { get; set; }
    }
}
