//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class groupXentity
    {
        public groupXentity()
        {
            this.commission = new HashSet<commission>();
            this.usersXgroup = new HashSet<usersXgroup>();
        }
    
        public int groupenti_id { get; set; }
        public string groupenti_description { get; set; }
        public int enti_id { get; set; }
        public int tview_id { get; set; }
    
        public virtual ICollection<commission> commission { get; set; }
        public virtual ICollection<usersXgroup> usersXgroup { get; set; }
    }
}
