//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class gtoclaims
    {
        public int gtocla_id { get; set; }
        public int claim_id { get; set; }
        public int gto_id { get; set; }
    
        public virtual claims claims { get; set; }
        public virtual gto gto { get; set; }
    }
}
