//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class homologacion
    {
        public int id { get; set; }
        public Nullable<int> id_plannuevadb { get; set; }
        public Nullable<int> id_planilotus { get; set; }
        public Nullable<int> serialplan { get; set; }
        public Nullable<int> serialpoliza { get; set; }
    }
}
