//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class impuesto
    {
        public impuesto()
        {
            this.impuestoXcountry = new HashSet<impuestoXcountry>();
        }
    
        public int impu_id { get; set; }
        public string impu_description { get; set; }
        public string impu_name { get; set; }
        public Nullable<double> impucoun_value { get; set; }
    
        public virtual ICollection<impuestoXcountry> impuestoXcountry { get; set; }
    }
}
