//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class infoXcontractXprod
    {
        public infoXcontractXprod()
        {
            this.configurationXcontractXproducts = new HashSet<configurationXcontractXproducts>();
        }
    
        public int info_id { get; set; }
        public string info_description { get; set; }
        public Nullable<int> info_peoplequantity { get; set; }
    
        public virtual ICollection<configurationXcontractXproducts> configurationXcontractXproducts { get; set; }
    }
}
