//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoices
    {
        public invoices()
        {
            this.collections = new HashSet<collections>();
        }
    
        public int invo_id { get; set; }
        public double invo_value { get; set; }
        public double invo_paidvalue { get; set; }
        public double invo_balance { get; set; }
        public System.DateTime invo_duedate { get; set; }
        public System.DateTime invo_paiddate { get; set; }
        public int sales_id { get; set; }
        public int status_id { get; set; }
    
        public virtual ICollection<collections> collections { get; set; }
        public virtual sales sales { get; set; }
        public virtual status status { get; set; }
    }
}
