//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class neighborhood
    {
        public neighborhood()
        {
            this.entity = new HashSet<entity>();
        }
    
        public int neig_id { get; set; }
        public string neig_name { get; set; }
        public int city_city_id { get; set; }
    
        public virtual city city { get; set; }
        public virtual ICollection<entity> entity { get; set; }
    }
}
