//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class paymenttype
    {
        public paymenttype()
        {
            this.sales = new HashSet<sales>();
        }
    
        public int ptype_id { get; set; }
        public string ptype_description { get; set; }
    
        public virtual ICollection<sales> sales { get; set; }
    }
}
