//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class periodpayment
    {
        public periodpayment()
        {
            this.configurationXcontractXproducts = new HashSet<configurationXcontractXproducts>();
        }
    
        public int ppay_id { get; set; }
        public string ppay_description { get; set; }
        public int ppay_time { get; set; }
    
        public virtual ICollection<configurationXcontractXproducts> configurationXcontractXproducts { get; set; }
    }
}
