//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class periodinactivation
    {
        public int perinac_id { get; set; }
        public string perinac_description { get; set; }
        public int perinac_days { get; set; }
        public Nullable<int> country_id { get; set; }
    
        public virtual country country { get; set; }
    }
}
