//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public products()
        {
            this.contractXproducts = new HashSet<contractXproducts>();
            this.productXapp = new HashSet<productXapp>();
            this.servicesXproduct = new HashSet<servicesXproduct>();
            this.productsXcountry = new HashSet<productsXcountry>();
            this.productsXotherproducts = new HashSet<productsXotherproducts>();
            this.productsXtreatments = new HashSet<productsXtreatments>();
        }
    
        public int product_id { get; set; }
        public string product_description { get; set; }
    
        public virtual ICollection<contractXproducts> contractXproducts { get; set; }
        public virtual ICollection<productXapp> productXapp { get; set; }
        public virtual ICollection<servicesXproduct> servicesXproduct { get; set; }
        public virtual ICollection<productsXcountry> productsXcountry { get; set; }
        public virtual ICollection<productsXotherproducts> productsXotherproducts { get; set; }
        public virtual ICollection<productsXtreatments> productsXtreatments { get; set; }
    }
}
