//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class productsXotherproducts
    {
        public int prodoprod_id { get; set; }
        public int oprod_id { get; set; }
        public int product_id { get; set; }
    
        public virtual otherproducts otherproducts { get; set; }
        public virtual products products { get; set; }
    }
}
