//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class productsXtreatments
    {
        public int prodtreat_id { get; set; }
        public Nullable<double> prodtreat_coverage { get; set; }
        public int product_id { get; set; }
        public int treat_id { get; set; }
    
        public virtual products products { get; set; }
        public virtual treatments treatments { get; set; }
    }
}
