//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class providers
    {
        public providers()
        {
            this.providerXcontract = new HashSet<providerXcontract>();
            this.usersXprovider = new HashSet<usersXprovider>();
        }
    
        public int prov_id { get; set; }
        public string prov_name { get; set; }
        public double prov_ucfactor { get; set; }
        public int tprov_id { get; set; }
    
        public virtual typeprovider typeprovider { get; set; }
        public virtual ICollection<providerXcontract> providerXcontract { get; set; }
        public virtual ICollection<usersXprovider> usersXprovider { get; set; }
    }
}
