//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class roles
    {
        public roles()
        {
            this.commission = new HashSet<commission>();
            this.rolesXuser = new HashSet<rolesXuser>();
            this.usertypeXapp = new HashSet<usertypeXapp>();
        }
    
        public int role_id { get; set; }
        public string role_description { get; set; }
        public int role_level { get; set; }
    
        public virtual ICollection<commission> commission { get; set; }
        public virtual ICollection<rolesXuser> rolesXuser { get; set; }
        public virtual ICollection<usertypeXapp> usertypeXapp { get; set; }
    }
}
