//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales
    {
        public sales()
        {
            this.appoiment = new HashSet<appoiment>();
            this.CommissionForSale = new HashSet<CommissionForSale>();
            this.invoices = new HashSet<invoices>();
        }
    
        public int sales_id { get; set; }
        public System.DateTime sales_buyingdate { get; set; }
        public System.DateTime sales_beginingdate { get; set; }
        public System.DateTime sales_enddate { get; set; }
        public string sales_sellerid { get; set; }
        public System.DateTime sales_dateinactivation { get; set; }
        public string user_id { get; set; }
        public int ptype_id { get; set; }
        public int status_id { get; set; }
        public Nullable<int> confcontractprod_id { get; set; }
        public Nullable<int> serial_ppac { get; set; }
        public string idsale_lotus { get; set; }
        public string idsale_mainly { get; set; }
    
        public virtual ICollection<appoiment> appoiment { get; set; }
        public virtual ICollection<CommissionForSale> CommissionForSale { get; set; }
        public virtual configurationXcontractXproducts configurationXcontractXproducts { get; set; }
        public virtual ICollection<invoices> invoices { get; set; }
        public virtual paymenttype paymenttype { get; set; }
        public virtual status status { get; set; }
        public virtual users users { get; set; }
    }
}
