//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class services
    {
        public services()
        {
            this.servicesXproduct = new HashSet<servicesXproduct>();
            this.servicesXnetwork = new HashSet<servicesXnetwork>();
            this.servicesXapp = new HashSet<servicesXapp>();
        }
    
        public int services_id { get; set; }
        public string services_description { get; set; }
    
        public virtual ICollection<servicesXproduct> servicesXproduct { get; set; }
        public virtual ICollection<servicesXnetwork> servicesXnetwork { get; set; }
        public virtual ICollection<servicesXapp> servicesXapp { get; set; }
    }
}
