//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class states
    {
        public states()
        {
            this.city = new HashSet<city>();
        }
    
        public int states_id { get; set; }
        public string states_name { get; set; }
        public int country_id { get; set; }
    
        public virtual ICollection<city> city { get; set; }
        public virtual country country { get; set; }
    }
}
