//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class statusXticket
    {
        public statusXticket()
        {
            this.ticket = new HashSet<ticket>();
        }
    
        public int statustick_id { get; set; }
        public string statustick_description { get; set; }
    
        public virtual ICollection<ticket> ticket { get; set; }
    }
}
