//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class statusclaims
    {
        public statusclaims()
        {
            this.glosastatusclaims = new HashSet<glosastatusclaims>();
        }
    
        public int stacla_id { get; set; }
        public System.DateTime stacla_datemodify { get; set; }
        public int stacla_usermodify { get; set; }
        public int stacla_userdentist { get; set; }
        public System.DateTime stacla_closedate { get; set; }
        public int claim_id { get; set; }
        public int status_id { get; set; }
    
        public virtual claims claims { get; set; }
        public virtual ICollection<glosastatusclaims> glosastatusclaims { get; set; }
        public virtual status status { get; set; }
    }
}
