//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tooth
    {
        public tooth()
        {
            this.characteristic_treatment = new HashSet<characteristic_treatment>();
        }
    
        public int tooth_id { get; set; }
        public int tooth_numberTooth { get; set; }
        public string tooth_description { get; set; }
    
        public virtual ICollection<characteristic_treatment> characteristic_treatment { get; set; }
    }
}
