//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class treatmentsXcountry
    {
        public int treatco_id { get; set; }
        public string treatco_codecountry { get; set; }
        public string treatco_description { get; set; }
        public int treat_id { get; set; }
        public int country_id { get; set; }
    
        public virtual country country { get; set; }
        public virtual treatments treatments { get; set; }
    }
}
