//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class treatments
    {
        public treatments()
        {
            this.characteristic_treatment = new HashSet<characteristic_treatment>();
            this.claims = new HashSet<claims>();
            this.glosaXtreatments = new HashSet<glosaXtreatments>();
            this.productsXtreatments = new HashSet<productsXtreatments>();
            this.treatmentsXcountry = new HashSet<treatmentsXcountry>();
        }
    
        public int treat_id { get; set; }
        public string treat_code { get; set; }
        public string treat_description { get; set; }
        public double treat_complex { get; set; }
    
        public virtual ICollection<characteristic_treatment> characteristic_treatment { get; set; }
        public virtual ICollection<claims> claims { get; set; }
        public virtual ICollection<glosaXtreatments> glosaXtreatments { get; set; }
        public virtual ICollection<productsXtreatments> productsXtreatments { get; set; }
        public virtual ICollection<treatmentsXcountry> treatmentsXcountry { get; set; }
    }
}
