//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class typeparticipation
    {
        public typeparticipation()
        {
            this.commission = new HashSet<commission>();
            this.contractXproducts = new HashSet<contractXproducts>();
        }
    
        public int typepartici_id { get; set; }
        public string typepartici_description { get; set; }
    
        public virtual ICollection<commission> commission { get; set; }
        public virtual ICollection<contractXproducts> contractXproducts { get; set; }
    }
}
