//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class typeprovider
    {
        public typeprovider()
        {
            this.providers = new HashSet<providers>();
        }
    
        public int tprov_id { get; set; }
        public string tprov_description { get; set; }
    
        public virtual ICollection<providers> providers { get; set; }
    }
}
