//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class uctreatconuntry
    {
        public int utreatco_id { get; set; }
        public double utreatco_value { get; set; }
        public System.DateTime utreatco_datefrom { get; set; }
        public System.DateTime utreatco_dateto { get; set; }
        public int country_id { get; set; }
        public int curren_id { get; set; }
    
        public virtual country country { get; set; }
        public virtual currency currency { get; set; }
    }
}
