//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.AddressXUser = new HashSet<AddressXUser>();
            this.AppXUser = new HashSet<AppXUser>();
            this.sales = new HashSet<sales>();
            this.useraudituc = new HashSet<useraudituc>();
            this.rolesXuser = new HashSet<rolesXuser>();
            this.usersXentity = new HashSet<usersXentity>();
            this.usersXprovider = new HashSet<usersXprovider>();
        }
    
        public string user_id { get; set; }
        public string user_icard { get; set; }
        public string user_firstname { get; set; }
        public string user_lastname { get; set; }
        public string user_icardtitular { get; set; }
        public int user_uc { get; set; }
        public int status_id { get; set; }
        public string user_email { get; set; }
        public string user_password { get; set; }
        public bool user_password_changed { get; set; }
        public System.DateTime user_last_activity { get; set; }
        public int user_lang { get; set; }
        public string user_sellerCode { get; set; }
        public Nullable<System.DateTime> user_birthdate { get; set; }
        public string user_gender { get; set; }
        public string user_cellphone { get; set; }
        public string user_address { get; set; }
        public Nullable<int> country_id { get; set; }
        public string user_urlimg { get; set; }
        public string CarNumber { get; set; }
        public Nullable<System.DateTime> user_creation { get; set; }
    
        public virtual ICollection<AddressXUser> AddressXUser { get; set; }
        public virtual ICollection<AppXUser> AppXUser { get; set; }
        public virtual country country { get; set; }
        public virtual languages languages { get; set; }
        public virtual ICollection<sales> sales { get; set; }
        public virtual ICollection<useraudituc> useraudituc { get; set; }
        public virtual ICollection<rolesXuser> rolesXuser { get; set; }
        public virtual ICollection<usersXentity> usersXentity { get; set; }
        public virtual ICollection<usersXprovider> usersXprovider { get; set; }
    }
}
