//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class usersXgroup
    {
        public int ugroup_id { get; set; }
        public string user_id { get; set; }
        public int groupenti_id { get; set; }
    
        public virtual groupXentity groupXentity { get; set; }
    }
}
