//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milton.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class validitytime
    {
        public validitytime()
        {
            this.configurationXcontractXproducts = new HashSet<configurationXcontractXproducts>();
        }
    
        public int vtime_id { get; set; }
        public string vtime_description { get; set; }
        public int vtime_days { get; set; }
    
        public virtual ICollection<configurationXcontractXproducts> configurationXcontractXproducts { get; set; }
    }
}
